--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/PocketShop
build-by-default: true
branches:
- main
projects:
  PocketShop:
    path: ""
    libs:
       - src: terpz710/pocketforms/PocketForms
         version: ^1.0.0
       - src: ACM-PocketMine-MP/Commando/Commando
         version: ^3.2.1
    lint: false
...
